#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$in_f <<EOF
5,6
5,6.0
5.0,6
5.0,6.0
5,5
5,4
5,4.0
5.0,4
5.0,4.0
5,0
5.0,0
5,0.0
5.0,0.0
5,-1
5.0,-1
5,-1.0
5.0,-1.0
EOF

cat >$correct_out_f <<EOF
true
true
true
true
false
false
false
false
false
false
false
false
false
false
false
false
false
EOF

run_test '-, $(&1.1 < &1.2)'




