#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$in_f <<EOF
a,bc
b,abc
bb,cc
,x
y,
,
EOF

cat >$correct_out_f <<EOF
abc,bca
babc,abcb
bbcc,ccbb
x,x
y,y
,
EOF

run_test '-, $(&1.1 ++ &1.2) $(&1.2 ++ &1.1)'




