#!/bin/bash

in_file=$(mktemp)
result_file=$(mktemp)
trap "rm $in_file $result_file" EXIT

cat >$in_file <<- EOF
blablable
EOF

cat >$result_file <<- EOF
17
EOF


if ./build/lsql-csv '-, $(5*5-2*2^2)' < $in_file | diff - $result_file; then
  echo "Test aritmetics successed."
  exit 0
else
  echo "Test aritmetics failed."
  exit 1
fi

