#!/bin/bash

in_file=$(mktemp)
result_file=$(mktemp)
trap "rm $in_file $result_file" EXIT

cat >$in_file <<- EOF
1
5
4
8
EOF

cat >$result_file <<- EOF
18
EOF


if ./build/lsql-csv '-, sum(&1.1)' < $in_file | diff - $result_file; then
  echo "Test grouping successed."
  exit 0
else
  echo "Test grouping failed."
  exit 1
fi

