#!/bin/bash

in_file=$(mktemp)
result_file=$(mktemp)
trap "rm $in_file $result_file" EXIT

cat >$in_file <<- EOF
name;"weird!name";"huhuhaha"
1;2;3
EOF

cat >$result_file <<- EOF
1;2;3
EOF


if ./build/lsql-csv -n 'in=-,&1.name `in.weird!name` in.3' < $in_file | diff - $result_file; then
  echo "Test named successed."
  exit 0
else
  echo "Test named failed."
  exit 1
fi

