#!/bin/bash

tmpfile=$(mktemp)
trap "rm $tmpfile" EXIT

cat >$tmpfile <<- EOF
city,population,id,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital
Tokyo,35676000,1392685764,Tokyo,35.685,139.7514,Japan,JP,JPN,"Tōk,yō",primary
EOF

if ./build/lsql-csv -d, '-,&*.{1..11}' < $tmpfile | diff - $tmpfile; then
  echo "Test secondary delimiter successed."
  exit 0
else
  echo "Test secondary delimiter failed."
  exit 1
fi


