#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$in_f <<EOF
5,ABCD,abcd
11,XXXX,xxxx
7,XYZ,xyz
EOF

cat >$correct_out_f <<EOF
11,XXXX,xxxx
7,XYZ,xyz
5,ABCD,abcd
EOF

run_test '-, &1.*, sort $(-&1.1)' 

