#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$in_f <<EOF
5,ABCD,abcd
11,XXXX,xxxx
7,XYZ,xyz
4,abcd,ABCD
EOF

cat >$correct_out_f <<EOF
7,XYZ,xyz
5,ABCD,abcd
EOF

run_test '-, &1.{1..3}, if &1.1 < 10, if &1.1 > 4, sort $(-&1.1)' 

