#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$tmp_f <<EOF
name,age
Adam,21
Petra,23
Karel,25
EOF

cat >$correct_out_f <<EOF
Adam,21,21,Adam
Petra,23,23,Petra
Karel,25,25,Karel
EOF

run_test -n "$tmp_f, &1.*"

