#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh


passwd_f=$tmp_folder/passwd_f
group_f=$tmp_folder/group_f

cat >$passwd_f <<EOF
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/bin/false
daemon:x:2:2:daemon:/sbin:/bin/false
lp:x:4:7:lp:/var/spool/lpd:/bin/false
halt:x:7:0:halt:/sbin:/sbin/halt
EOF

cat >$group_f <<EOF
root:x:0:root,halt
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
lp:x:7:lp
wheel:x:10:root,halt
floppy:x:11:root
tape:x:26:root
EOF


cat >$correct_out_f <<EOF
bin:bin,daemon,
daemon:bin,daemon,
halt:root,wheel,
lp:lp,
root:bin,daemon,floppy,root,tape,wheel,
EOF


run_test -d: "p=$passwd_f g=$group_f, "'
  p.1 cat(g.1","), if p.1 in g.4, by p.1'

