#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh


left_f=$tmp_folder/left_f
left_mid_f=$tmp_folder/left_mid_f
right_mid_f=$tmp_folder/right_mid_f
right_f=$tmp_folder/right_f

cat >$left_f <<EOF
1,A
2,B
3,C
4,D
EOF

cat >$left_mid_f <<EOF
4,d
3,c
2,b
1,a
EOF

cat >$right_mid_f <<EOF
4,Dd
3,Cc
2,Bb
1,Aa
EOF

cat >$right_f <<EOF
3,CC
1,AA
2,BB
4,DD
EOF

cat >$correct_out_f <<EOF
A,a,Aa,AA
B,b,Bb,BB
C,c,Cc,CC
D,d,Dd,DD
EOF


run_test "$left_f $left_mid_f $right_mid_f $right_f, &1.2 &2.2 &3.2 &4.2, if &1.1 == &2.1 && &2.1 == &3.1 && &3.1 == &4.1"

