#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$tmp_f <<EOF
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/bin/false
daemon:x:2:2:daemon:/sbin:/bin/false
adm:x:3:4:adm:/var/adm:/bin/false
lp:x:4:7:lp:/var/spool/lpd:/bin/false
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
nobody:x:65534:65534:nobody:/var/empty:/bin/false
news:x:9:13:news:/var/spool/news:/bin/false
uucp:x:10:14:uucp:/var/spool/uucp:/bin/false
operator:x:11:0:operator:/root:/sbin/nologin
me:x:1000:1000::/home/me:/bin/bash
EOF

cat >$correct_out_f <<EOF
The number of users of /bin/bash is 2.
The number of users of /bin/false is 7.
The number of users of /bin/sync is 1.
The number of users of /sbin/halt is 1.
The number of users of /sbin/nologin is 1.
The number of users of /sbin/shutdown is 1.
EOF


run_test -d: "p=$tmp_f"',
  "The number of users of "p.7" is "count(p.3)".", by p.7'

