#!/usr/bin/env sh
. $(dirname $0)/../testlib.sh

cat >$tmp_f <<EOF
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/bin/false
daemon:x:2:2:daemon:/sbin:/bin/false
adm:x:3:4:adm:/var/adm:/bin/false
lp:x:4:7:lp:/var/spool/lpd:/bin/false
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
me2:x:1001:1001::/home/me2:/bin/bash
nobody:x:65534:65534:nobody:/var/empty:/bin/false
me3:x:1002:1002::/home/me3:/bin/bash
news:x:9:13:news:/var/spool/news:/bin/false
uucp:x:10:14:uucp:/var/spool/uucp:/bin/false
operator:x:11:0:operator:/root:/sbin/nologin
me1:x:1000:1000::/home/me1:/bin/bash
EOF

cat >$correct_out_f <<EOF
me1:x:1000:1000::/home/me1:/bin/bash
me2:x:1001:1001::/home/me2:/bin/bash
me3:x:1002:1002::/home/me3:/bin/bash
nobody:x:65534:65534:nobody:/var/empty:/bin/false
EOF

run_test -d: "$tmp_f, &1.*, if &1.3 >= 1000, sort &1.3"

